  name: build
  on: push

  jobs:
    build:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set Node.js 10.x
          uses: actions/setup-node@v3
          with:
            node-version: 10.x  

        - name: Python 2
          uses: actions/setup-python@v4
          with:
            python-version: '2.7.18' 
            
        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install # will run `yarn install` command

        - name: Build
          uses: borales/actions-yarn@v4
          with:
            cmd: build



